/**
 * All display copy, both languages, in one file.
 *
 * The backend returns machine codes ("below_threshold", "no_anchor"), never
 * sentences. Copy lives here so both language sets are reviewed at one gate and
 * glossary terms stay consistent; a status code split across two layers is how
 * half-translated UIs happen.
 */
import type { Lang } from "./format";

export const dict = {
  ar: {
    dir: "rtl" as const,
    title: "منصة الذكاء السوقي السعودي",
    brandName: "CustodAI",
    terminal: "TERMINAL",
    command: "الأمر",
    commandHint: "أرامكو · رؤية ٢٠٣٠ · أسعار الفائدة · وثائق ٢٠٢٦",
    suggested: "مقترحات",
    extractiveNote: "مقاطع مقتبسة من مصادر موثقة",
    startPrompt: "ابدأ بالبحث عن شركة أو خبر أو نظام أو حدث اقتصادي.",
    live: "مباشر",
    riyadh: "الرياض",
    connected: "متصل",
    workspace: "مساحة العمل",
    docsIndexed: "وثيقة مفهرسة",
    marketPulse: "نبض السوق",
    pulseHeadline: "أحدث ما رصدته المنصة عبر الأخبار والإفصاحات والأنظمة والتمويل.",
    tracked: "متابَع لك",
    taggedDocs: "وثيقة مرتبطة بشركة",
    companiesCovered: "شركة مغطّاة",
    portfolio: "مراقب المحفظة",
    tickers: "أسهم",
    sampleShort: "تجريبي",
    ticker: "الرمز",
    company: "الشركة",
    last: "الأخير",
    chg: "التغير",
    trend7: "الاتجاه",
    sectorHeat: "خريطة القطاعات",
    sizeWeight: "الحجم = وزن المؤشر",
    newsFilings: "الأخبار والإفصاحات",
    liveCoverage: "تغطية حية",
    trendingTitle: "الأكثر تداولاً",
    byMentions: "حسب عدد الإشارات",
    mentions: "إشارة",
    timeline: "الجدول الزمني",
    fromCorpus: "من المرجع المنسّق",
    periodChange: "تغير الفترة",
    high: "الأعلى",
    low: "الأدنى",
    trendLabel: "الاتجاه",
    trendUp: "صاعد",
    trendDown: "هابط",
    quoteUnavailable: "السعر غير متاح",
    priceChart: "الرسم البياني للسعر",
    smaLegend: "المتوسطات المتحركة 20 و50",
    close: "الإغلاق",
    sampleNote: "سلسلة تجريبية — البيانات التاريخية محجوبة في الباقة المجانية",
    context: "السياق",
    contextSub: "أنظمة · توجّهات · ملكية · جيوسياسة",
    noContext: "لا يوجد سياق مرتبط",
    noData: "لا توجد بيانات",
    marketData: "بيانات السوق",
    realShort: "مباشر",
    open_: "الافتتاح",
    prevClose: "الإغلاق السابق",
    dayRange: "نطاق اليوم",
    volume: "الكمية",
    turnover: "قيمة التداول",
    bid: "أفضل شراء",
    ask: "أفضل بيع",
    moneyFlow: "تدفق السيولة",
    inflow: "تدفق داخل",
    outflow: "تدفق خارج",
    netFlow: "صافي التدفق",
    trades: "صفقة",
    shares: "سهم",
    performance: "الأداء",
    p1d: "يوم",
    p5d: "5 أيام",
    p1m: "شهر",
    p3m: "3 أشهر",
    p6m: "6 أشهر",
    techSignal: "الإشارة الفنية",
    technical: "فني",
    bullish: "اتجاه صاعد",
    bearish: "اتجاه هابط",
    neutralSig: "محايد",
    notAdvice: "قراءة فنية للسلسلة السعرية، وليست توصية استثمارية.",
    summary: "الملخص",
    quoteSummary: "ملخص التداول",
    week52: "نطاق 52 أسبوعاً",
    marketCap: "القيمة السوقية",
    peRatio: "مكرر الربحية",
    eps: "ربحية السهم",
    rsiLabel: "مؤشر القوة النسبية",
    fundamentalsNote: "القيمة السوقية والمكرر وربحية السهم تتطلب بيانات مالية مرخّصة (محجوبة في الباقة المجانية).",
    deepResearch: "بحث معمّق",
    deepResearchBtn: "بحث معمّق",
    documents: "وثيقة",
    companiesInvolved: "الشركات ذات الصلة",
    researchPrompt: "ابدأ بحثاً معمّقاً من صفحة البحث.",
    recentLbl: "الأحدث",
    openDashboard: "افتح لوحة الشركة",
    updatedNow: "حُدّث الآن",
    tagline: "بحث واحد في كل ما يحرّك السهم",
    searchPlaceholder: "ابحث في الأخبار والإفصاحات والأنظمة والتمويل…",
    searchButton: "بحث",
    searching: "جارٍ البحث…",
    warmingUp: "جارٍ تجهيز محرك البحث…",
    answer: "الإجابة",
    sources: "المصادر",
    results: "النتائج",
    noResults: "لا توجد نتائج مطابقة",
    belowThreshold: "لم نجد ما يطابق هذا السؤال في المصادر المتاحة.",
    noAnchor: "لم نتعرف على هذا السؤال. جرّب اسم شركة أو موضوعاً اقتصادياً.",
    tryThese: "جرّب:",
    latestNews: "آخر الأخبار",
    noNews: "لا توجد أخبار مرتبطة",
    delayed: "مؤجل ١٥ دقيقة",
    delayedLatn: "مؤجل 15 دقيقة",
    stale: "من الذاكرة المؤقتة",
    sample: "بيانات تجريبية",
    asOf: "حتى",
    error: "تعذّر جلب البيانات",
    sector: "القطاع",
    dm: "الرسائل",
    dmSample: "شخصيات تجريبية",
    dmEmpty: "لا توجد رسائل",
    dmPlaceholder: "اكتب رسالة…",
    send: "إرسال",
    share: "مشاركة",
    shareTo: "مشاركة مع:",
    shared: "تم الإرسال",
    backToSearch: "رجوع للبحث",
    sharedArticle: "مقال مشترك",
    account: {
      heading: "الحساب",
      demoBadge: "حساب تجريبي · بيانات نموذجية",
      personaName: "مستثمر تجريبي",
      firmLabel: "الشركة",
      firm: "شركاء الرياض للاستثمار",
      seatLabel: "المقعد والدور",
      seat: "محلّل أول · مقعد واحد من ٣",
      licenceLabel: "الترخيص",
      licenceStatus: "نشط",
      plan: "الباقة الاحترافية (تجريبية)",
      licenceNote: "وصول كامل لطبقات الأخبار والإفصاحات والبحث الدلالي في هذا العرض.",
      renewalLabel: "التجديد والفوترة",
      renewalOn: "يُجدّد في",
      renewalDate: "٣١ يناير ٢٠٢٧",
      seatsLabel: "المقاعد",
      seatsVal: "١ مستخدم من ٣",
      billingOwnerLabel: "مالك الفوترة",
      watchlistLabel: "قائمة المتابعة",
      watchlistNote: "الأسهم التي تتابعها — من مراقب المحفظة.",
      entitlementsLabel: "صلاحيات البيانات",
      entLiveLabel: "مضمّن",
      entLockedLabel: "محجوب في الباقة المجانية",
      entLive: ["الأخبار والإفصاحات", "الأنظمة والتوجّهات", "البحث الدلالي", "لوحات الشركات", "الإشارة الفنية"],
      entLocked: ["الأساسيات (مكرر الربحية · ربحية السهم)", "السلاسل التاريخية الكاملة", "التسعير اللحظي (متاح مؤجّلاً ١٥ دقيقة)"],
      savedLabel: "عمليات بحث محفوظة",
      alertsLabel: "التنبيهات",
      savedSearches: ["توزيعات stc", "طرح أرامكو", "نظام الشركات الجديد"],
      alerts: ["stc — أي إفصاح جديد", "أرامكو — تحرّك السعر > ٣٪", "قطاع الطاقة — إفصاحات جديدة"],
    },
    docTypes: {
      news: "خبر", disclosure: "إفصاح", registry: "سجل", law: "نظام",
      mandate: "توجّه", funding: "تمويل", ownership: "ملكية",
      geopolitics: "جيوسياسة", dataset: "بيانات", corpus: "مرجع",
    } as Record<string, string>,
  },
  en: {
    dir: "ltr" as const,
    title: "KSA Market Intelligence",
    brandName: "CustodAI",
    terminal: "TERMINAL",
    command: "Command",
    commandHint: "Aramco · Vision 2030 · Rate path · 2026 filings",
    suggested: "Suggested",
    extractiveNote: "Extracted from cited sources",
    startPrompt: "Start by searching a company, a headline, a regulation, or an economic event.",
    live: "Live",
    riyadh: "Riyadh",
    connected: "Connected",
    workspace: "Workspace",
    docsIndexed: "documents indexed",
    marketPulse: "Market Pulse",
    pulseHeadline: "The latest across news, disclosures, regulation and funding, as captured by the index.",
    tracked: "Tracked for you",
    taggedDocs: "company-linked docs",
    companiesCovered: "companies covered",
    portfolio: "Portfolio Monitor",
    tickers: "tickers",
    sampleShort: "SAMPLE",
    ticker: "Ticker",
    company: "Company",
    last: "Last",
    chg: "Chg",
    trend7: "Trend",
    sectorHeat: "Sector Heatmap",
    sizeWeight: "Size = index weight",
    newsFilings: "News & Filings",
    liveCoverage: "Live coverage",
    trendingTitle: "Trending Companies",
    byMentions: "by mentions",
    mentions: "docs",
    timeline: "Timeline",
    fromCorpus: "from curated corpus",
    periodChange: "Period",
    high: "High",
    low: "Low",
    trendLabel: "Trend",
    trendUp: "Uptrend",
    trendDown: "Downtrend",
    quoteUnavailable: "Quote unavailable",
    priceChart: "Price Chart",
    smaLegend: "SMA 20 & 50",
    close: "Close",
    sampleNote: "Sample series — historical data is paywalled on the free tier",
    context: "Context",
    contextSub: "Regulation · mandates · ownership · geopolitics",
    noContext: "No linked context",
    noData: "No data",
    marketData: "Market Data",
    realShort: "REAL",
    open_: "Open",
    prevClose: "Prev Close",
    dayRange: "Day Range",
    volume: "Volume",
    turnover: "Turnover",
    bid: "Bid",
    ask: "Ask",
    moneyFlow: "Money Flow",
    inflow: "Inflow",
    outflow: "Outflow",
    netFlow: "Net Flow",
    trades: "trades",
    shares: "shares",
    performance: "Performance",
    p1d: "1D",
    p5d: "5D",
    p1m: "1M",
    p3m: "3M",
    p6m: "6M",
    techSignal: "Technical Signal",
    technical: "TECHNICAL",
    bullish: "Bullish",
    bearish: "Bearish",
    neutralSig: "Neutral",
    notAdvice: "A technical read of the price series, not investment advice.",
    summary: "Summary",
    quoteSummary: "Quote summary",
    week52: "52-Week Range",
    marketCap: "Market Cap",
    peRatio: "P/E Ratio",
    eps: "EPS",
    rsiLabel: "RSI (14)",
    fundamentalsNote: "Market cap, P/E and EPS need licensed fundamentals (paywalled on the free tier).",
    deepResearch: "Deep Research",
    deepResearchBtn: "Deep research",
    documents: "documents",
    companiesInvolved: "Companies involved",
    researchPrompt: "Start a deep research from the search page.",
    recentLbl: "Latest",
    openDashboard: "Open company dashboard",
    updatedNow: "updated just now",
    tagline: "One search across everything that moves a stock",
    searchPlaceholder: "Search news, disclosures, regulation, funding…",
    searchButton: "Search",
    searching: "Searching…",
    warmingUp: "Warming up the search engine…",
    answer: "Answer",
    sources: "Sources",
    results: "Results",
    noResults: "No matching results",
    belowThreshold: "Nothing in the indexed sources matches this closely enough.",
    noAnchor: "That query has no anchor in the corpus. Try a company or an economic topic.",
    tryThese: "Try:",
    latestNews: "Latest news",
    noNews: "No linked news",
    delayed: "15-min delayed",
    delayedLatn: "15-min delayed",
    stale: "from cache",
    sample: "sample data",
    asOf: "as of",
    error: "Could not load market data",
    sector: "Sector",
    dm: "Messages",
    dmSample: "sample personas",
    dmEmpty: "No messages",
    dmPlaceholder: "Write a message…",
    send: "Send",
    share: "Share",
    shareTo: "Share with:",
    shared: "Sent",
    backToSearch: "Back to search",
    sharedArticle: "Shared article",
    account: {
      heading: "Account",
      demoBadge: "Demo account · sample data",
      personaName: "Demo Investor",
      firmLabel: "Firm",
      firm: "Riyadh Capital Partners",
      seatLabel: "Seat & role",
      seat: "Senior Analyst · 1 of 3 seats",
      licenceLabel: "Licence",
      licenceStatus: "Active",
      plan: "Professional (Demo)",
      licenceNote: "Full access to the news, disclosure and semantic-search tiers in this demo.",
      renewalLabel: "Billing & renewal",
      renewalOn: "Renews on",
      renewalDate: "31 Jan 2027",
      seatsLabel: "Seats",
      seatsVal: "1 of 3 users",
      billingOwnerLabel: "Billing owner",
      watchlistLabel: "Watchlist",
      watchlistNote: "The tickers you follow — from the Portfolio Monitor.",
      entitlementsLabel: "Data entitlements",
      entLiveLabel: "Included",
      entLockedLabel: "Free-tier locked",
      entLive: ["News & disclosures", "Regulation & mandates", "Semantic search", "Company terminals", "Technical signal"],
      entLocked: ["Fundamentals (P/E · EPS)", "Full historical series", "Real-time quotes (15-min delayed only)"],
      savedLabel: "Saved searches",
      alertsLabel: "Alerts",
      savedSearches: ["stc dividends", "saudi aramco ipo", "new companies law"],
      alerts: ["stc — any new disclosure", "Aramco — price move > 3%", "Energy sector — new filings"],
    },
    docTypes: {
      news: "News", disclosure: "Disclosure", registry: "Registry", law: "Law",
      mandate: "Mandate", funding: "Funding", ownership: "Ownership",
      geopolitics: "Geopolitics", dataset: "Dataset", corpus: "Reference",
    } as Record<string, string>,
  },
};

export type Dict = (typeof dict)["ar"];

export const isLang = (v: string): v is Lang => v === "ar" || v === "en";

export const SUGGESTIONS: Record<Lang, string[]> = {
  // Every one of these is backed by a document verified present in the index.
  ar: [
    "عقد أرامكو مع هاليبرتون لتطوير الغاز",
    "نتائج المراعي الربع الثاني",
    "رؤية السعودية 2030",
    "نظام الشركات الجديد",
  ],
  en: ["aramco helicopter crash", "stc dividends", "saudi aramco ipo"],
};
